In [2]:
import pandas as pd

In [7]:
df = pd.read_excel('data.xlsx')

In [8]:
df

,MAKANAN DAN MINUMAN JADI,ROTI TAWAR,ROTI MANIS DAN LAINNYA,KUE KERING BISKUIT SEMPRONG,KUE BASAH,MAKANAN GORENG,BUBUR KACANG HIJAU,GADO GADO KETOPRAK,NASI CAMPUR RAMES,NASI GORENG,...,BUBUR AYAM,SIOMAY BATAGO,MAKANAN JADI LAINNYA,AIR KEMASAN,AIR GALON,AIR TEH KEMASAN DAN BERSODA,SARI BUAH KEMASAN MINUMAN KESEHATAN,MINUMAN JADI KOPI SUSU,ES KRIM,ES LAINNYA
0,23744,46,348,411,3903,1877,154,54,1277,693,...,15,164,94,137,1587,78,313,4114,396,286
1,26997,1077,1093,566,1309,2966,558,611,632,2166,...,54,270,201,254,1134,118,145,2253,876,356
2,38327,166,1021,710,3243,2531,329,256,8938,991,...,11,449,98,237,476,329,425,4892,862,335
3,28338,254,761,514,1710,2488,363,443,1234,1525,...,110,1478,172,466,546,312,613,3634,822,414
4,39395,330,790,549,2644,2625,929,227,4189,2833,...,171,1062,269,645,748,506,366,7494,1166,258
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
509,8898,-,-,755,115,6958,-,-,-,21,...,-,-,-,49,436,-,-,-,-,-
510,4992,92,486,133,124,645,22,-,1592,42,...,-,-,11,74,3,611,140,679,-,-
511,1468,153,9,7,5,542,-,-,282,13,...,-,-,-,124,-,188,-,9,-,15
512,-,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
513,56616,795,1165,912,3382,1873,560,2051,10783,4084,...,663,491,3543,2021,2563,1114,678,2301,648,981

In [9]:
df.head(20)

,MAKANAN DAN MINUMAN JADI,ROTI TAWAR,ROTI MANIS DAN LAINNYA,KUE KERING BISKUIT SEMPRONG,KUE BASAH,MAKANAN GORENG,BUBUR KACANG HIJAU,GADO GADO KETOPRAK,NASI CAMPUR RAMES,NASI GORENG,...,BUBUR AYAM,SIOMAY BATAGO,MAKANAN JADI LAINNYA,AIR KEMASAN,AIR GALON,AIR TEH KEMASAN DAN BERSODA,SARI BUAH KEMASAN MINUMAN KESEHATAN,MINUMAN JADI KOPI SUSU,ES KRIM,ES LAINNYA
0,23744,46,348,411,3903,1877,154,54,1277,693,...,15,164,94,137,1587,78,313,4114,396,286
1,26997,1077,1093,566,1309,2966,558,611,632,2166,...,54,270,201,254,1134,118,145,2253,876,356
2,38327,166,1021,710,3243,2531,329,256,8938,991,...,11,449,98,237,476,329,425,4892,862,335
3,28338,254,761,514,1710,2488,363,443,1234,1525,...,110,1478,172,466,546,312,613,3634,822,414
4,39395,330,790,549,2644,2625,929,227,4189,2833,...,171,1062,269,645,748,506,366,7494,1166,258
5,48300,546,1892,2137,2858,3407,441,622,6242,1894,...,178,2681,534,366,881,158,814,4551,1043,281
6,67356,380,1667,850,3996,3559,858,494,12556,4494,...,132,679,1433,634,1703,806,880,7934,1370,2056
7,51446,586,1666,1150,4876,2675,645,347,1691,3406,...,294,1982,214,369,1913,692,1017,9363,1167,235
8,53479,435,1365,1479,4955,4343,852,445,4241,4067,...,34,1496,229,436,1016,770,1747,7788,1314,667
9,56157,185,1261,1575,5058,3410,492,398,6413,2947,...,118,2236,949,1015,785,371,997,8952,1399,916
10,32540,273,778,568,2974,2106,610,242,509,2031,...,73,2038,157,161,464,264,713,7052,915,354
11,34579,192,767,932,2584,2276,158,209,10221,1140,...,26,389,182,817,722,413,230,3857,863,238
12,55610,586,1479,1290,2186,4008,928,531,13557,1079,...,58,955,593,234,672,390,411,4636,1456,287
13,32408,206,1068,849,1171,2102,232,166,3853,1256,...,43,1637,359,229,1396,245,206,2629,815,483
14,58733,473,939,845,3020,3178,1061,619,19016,2823,...,59,1018,315,268,955,547,471,6494,1532,1183
15,57598,314,1507,1830,4935,3645,778,267,6184,3749,...,3,1245,377,865,904,934,689,9361,1486,970
16,44421,266,1109,1356,4084,4234,301,777,8969,939,...,47,1834,79,200,266,186,340,4572,856,88
17,54615,760,1449,1458,5323,3556,735,729,2956,4107,...,65,2189,1463,601,920,855,810,9473,1644,258
18,104906,879,2290,1499,5459,2309,440,726,19184,6117,...,866,2489,4524,2457,4210,1682,1380,13975,1318,3986
19,69934,338,1163,1878,6490,3279,583,658,10050,3529,...,548,2502,880,1208,2430,595,1260,9138,1076,1192